feat: sonarcube 테스트 커버리지 측정 CI에 추가

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -43,6 +43,42 @@ jobs:
       - name: Build all modules with Maven
         run: mvn clean install -DskipTests=true -B
 
+  sonar-analysis:
+    name: SonarQube Analysis
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v3
+        with:
+          distribution: temurin
+          java-version: 21
+
+      - name: SonarQube Scan
+        run: |
+          mvn verify sonar:sonar \
+            -Dsonar.projectKey=ink3_gateway \
+            -Dsonar.projectName='ink3_gateway' \
+            -Dsonar.host.url=http://s4.java21.net:9000 \
+            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
+            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
+
+      - name: Check coverage threshold
+        run: |
+          LINE_COVERAGE=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
+          LINE_MISSED=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
+          TOTAL=$((LINE_COVERAGE + LINE_MISSED))
+          PERCENT=$((LINE_COVERAGE * 100 / TOTAL))
+          echo "Coverage: $PERCENT%"
+  #          if [ "$PERCENT" -lt 60 ]; then
+  #            echo "Coverage is below 60%! Failing build."
+  #            exit 1
+  #          fi
+
   test:
     needs: build
     runs-on: ubuntu-latest
@@ -56,7 +92,7 @@ jobs:
         with:
           distribution: temurin
           java-version: 21
-          
+
       - name: Extract version from POM
         id: extract_version
         run: |
