feat: dev CI/CD 설정

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -3,10 +3,10 @@ name: CI
 on:
   push:
     branches:
-      - main
+      - dev
   pull_request:
     branches:
-      - main
+      - dev
 
 jobs:
   build:
@@ -43,6 +43,45 @@ jobs:
       - name: Build all modules with Maven
         run: mvn clean install -DskipTests=true -B
 
+  sonar-analysis:
+    name: SonarQube Analysis
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v3
+        with:
+          distribution: temurin
+          java-version: 21
+
+      - name: SonarQube Analysis
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          mvn clean verify -Dspring.profiles.active=test sonar:sonar \
+            -Dsonar.projectKey=ink3_gateway \
+            -Dsonar.projectName='ink3_gateway' \
+            -Dsonar.host.url=http://s4.java21.net:9000 \
+            -Dsonar.token=$SONAR_TOKEN \
+            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
+
+
+      - name: Check coverage threshold
+        run: |
+          LINE_COVERAGE=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
+          LINE_MISSED=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
+          TOTAL=$((LINE_COVERAGE + LINE_MISSED))
+          PERCENT=$((LINE_COVERAGE * 100 / TOTAL))
+          echo "Coverage: $PERCENT%"
+    #          if [ "$PERCENT" -lt 60 ]; then
+    #            echo "Coverage is below 60%! Failing build."
+    #            exit 1
+    #          fi
+
   test:
     needs: build
     runs-on: ubuntu-latest
@@ -56,7 +95,7 @@ jobs:
         with:
           distribution: temurin
           java-version: 21
-          
+
       - name: Extract version from POM
         id: extract_version
         run: |
@@ -70,9 +109,12 @@ jobs:
         run: mvn package -DskipTests=true -B
 
       - name: Run application in background
+        env:
+          EUREKA_URL: ${{ secrets.DEV_EUREKA_URL }}
         run: |
-          nohup java -jar target/gateway-${{ steps.extract_version.outputs.version }}.jar --server.port=10250 > app.log 2>&1 &
+          nohup java -jar target/gateway-${{ steps.extract_version.outputs.version }}.jar --server.port=10265 > app.log 2>&1 &
           echo $! > app.pid
+
 
       - name: Wait for application to start
         run: sleep 15
@@ -81,12 +123,14 @@ jobs:
         run: ls -lh target/gateway-${{ steps.extract_version.outputs.version }}.jar
 
       - name: Check health endpoint
-        run: curl --fail http://localhost:10250/actuator/health
+        run: curl --fail http://localhost:10265/actuator/health
 
       - name: Stop application
         run: kill $(cat app.pid)
 
       - name: Run unit tests
+        env:
+          EUREKA_URL: ${{ secrets.DEV_EUREKA_URL }}
         run: mvn test -B
 
       - name: Print app log if health check fails
@@ -131,7 +175,7 @@ jobs:
           username: ${{ secrets.SSH_ID }}
           key: ${{ secrets.SSH_KEY }}
           source: "target/*.jar"
-          target: "~/ink3-server/gateway"
+          target: "~/ink3-server-dev/gateway-dev"
 
       - name: Run deploy.sh on server
         uses: appleboy/ssh-action@v0.1.7
@@ -141,7 +185,9 @@ jobs:
           username: ${{ secrets.SSH_ID }}
           key: ${{ secrets.SSH_KEY }}
           script: |
-            cd ~/ink3-server/gateway
+            cd ~/ink3-server-dev/gateway-dev
             chmod +x deploy.sh
+            export EUREKA_URL=${{ secrets.DEV_EUREKA_URL }}
             nohup ./deploy.sh > deploy.log 2>&1 &
             exit 0
+            
